# Generated by Django 4.1.7 on 2023-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_blogpost_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='title',
        ),
    ]
