# Generated by Django 4.1.7 on 2023-03-29 21:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_created_at_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_image_upload_path),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='safe',
            field=models.BooleanField(default=True),
        ),
    ]
