# Generated by Django 4.1.7 on 2023-04-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_usertag_blogpost_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertags', to='blog.blogpost'),
        ),
    ]
