# Generated by Django 4.1.7 on 2023-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
